# Generated by Django 2.1.7 on 2019-04-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siderbar',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
