# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20190505_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
