# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190505_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=150, verbose_name='评论目标'),
        ),
    ]
